### PR TITLE
feat(symbolwinbar): Add click support

### PR DESCRIPTION
**Pull request by nullchilly**
Forgot to add this along with the previous pull request, hope you don't mind :)

I think using [stylua](https://github.com/JohnnyMorganz/StyLua) would be nice here since the coding style is pretty inconsistent

Also, writing [plenary tests](https://github.com/nvim-lua/plenary.nvim#plenarytest_harness) will help big time here since this is a relatively big repo...

### CODE REVIEW

**Comment by glepnir** [comment]
I already install `stylua` but I am lazy to format:)

about `0` or `current_win` .I most like use `current_win` To be honest I didn't look at the implementation of 0. If there is no time consuming or memory consumption compared to  `currentwin`. I prefer to use `currentwin` to be more intuitive. 0 looks weird.

**Comment by nullchilly** [comment]
@glepnir Adding click support, can you review?

**Comment by glepnir** [comment]
@nullchilly  Please resolve conflict. I don't use mouse :) .when you resolve conflict I will merge .

**Comment by nullchilly** [comment]
I am so bad at resolving conflict ._.

**Comment by nullchilly** [comment]
Hmm I need to create a table in order to support right click

**Comment by glepnir** [comment]
why not

**Comment by nullchilly** [comment]
I don't understand... The middle stops working after a while

https://user-images.githubusercontent.com/56817415/177562652-a0a710c9-40d9-4b76-97d6-835ef6dbedb7.mp4

**Comment by nullchilly** [comment]
`fatal: unable to access 'https://github.com/nullchilly/lspsaga.nvim/': Failed to connect to g
ithub.com port 443 after 115 ms: Connection refused` :)

**Comment by nullchilly** [comment]
@glepnir I don't understand why is it conflict if I add an option in `lspsaga/init.lua`?

**Comment by nullchilly** [comment]
Oof I actually need to learn how to use git :(

**Comment by nullchilly** [comment]
I learned rebase D:

**Pull request closed without merging**
