### PR TITLE
improve behavior

### LINKED ISSUE #156: Allow for using a table of action_keys for more than only the quit key
**Is your feature request related to a problem? Please describe.**
Allow for defining a table for all the action keys and not only the `quit` key.

**Describe the solution you'd like**
Would be nice if something like this was allowed
```lua
require('lspsaga').init_lsp_saga({
  finder_action_keys = {
    open = { 'o', '<CR>' }, -- This is currently not supported
    quit = { 'q', '<ESC>' },
  }
})
```

Currently a table is only supported for the `quit` key.

### PR DESCRIPTION
**Pull request by glepnir**
refactor window and fix #156 #152 #166 #170

### CODE REVIEW

**Comment by Sduby22** [comment]
Code action window won't open again after using `:bd` command to close it.

```
Error executing vim.schedule lua callback: .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/codeaction.lua:123: Invalid buffer id: 6
```

worked fine when using <q> or `:q` to exit the action window

**Comment by glepnir** [comment]
@Sduby22  why use `:bd` to close codeaction window. you can use q and esc or some keymap that you like.

**Comment by glepnir** [comment]
maybe ready to merge. does anyone get problem in this branch？

**Comment by tami5** [comment]
I lost the cool border and action sometime get pasted in the buffer or I get error:

```
Error executing vim.schedule lua callback: ...m-nightly-master/share/nvim/runtime/lua/vim/lsp/util.lua:1223: attempt to compare number with nil
```

**Comment by tami5** [comment]
Okay something todo with recent change in neovim master that causing the action to stop working

**Comment by tami5** [comment]
Still I have no broder

**Comment by glepnir** [comment]
@tami5  hmm.. did you update neovim?

**Pull request merged**
