### PR TITLE
breaking change: finder and outline

### PR DESCRIPTION
**Pull request by YuCao16**
This PR has two contributors,
1. (breaking change) Add handler to control the height of finder. This update change finder's config table, move key binding to a new key table like other sections.
2. Add config to control enter outline with/without focus.

### CODE REVIEW

**Comment by glepnir** [comment]
just wonder the situation that you want make outline not focus. avoid the wincmd jump into it when you have multiple window right ?

**Comment by glepnir** [comment]
just wonder the situation that you want make outline not focus. avoid the wincmd jump into it when you have multiple window right ?

**Comment by YuCao16** [comment]
> just wonder the situation that you want make outline not focus. avoid the wincmd jump into it when you have multiple window right ?

Yes, sort of. Not all the time I open outline is to go to some location, sometims just want to check the file structure.

**Comment by YuCao16** [comment]
What do you think about the max_height config, any idea to avoid breaking change?

**Comment by glepnir** [comment]
tha is fine I think but in next version will  better. only preview no meanless .support edit would better . so I am refactor preview win now. so I will add this into this version

**Comment by glepnir** [comment]
finder improve in #810  . allowed edit in preview window. can you test the new finder ? and currently I disabled lsp in preview window. in huge project this will load many buffers  may spawn multiple servers. so I disabled it by default.

**Comment by YuCao16** [comment]
> finder improve in #810 . allow edit in preview window. can you test the new finder ? and currently I disabled lsp in preview window. in huge project this will load many buffers may spawn multiple servers. so I disabled it by default.

You may not be able to reproduce, but here is a bug.

[Screencast from 01-02-23 09:38:48.webm](https://user-images.githubusercontent.com/62466929/216006566-bd183441-131b-4403-9015-43b27f481c54.webm)

In addition, after entering finder, cursor is not at the top of the window.

**Comment by glepnir** [comment]
> In addition, after entering finder, cursor is not at the top of the window.

what do you mean in it first definition line ? you video works fine.  only bug is preview window not disappear

**Pull request closed without merging**
