### PR TITLE
lspsaga is incompatible with nvim 0.5.1 and nightly

### LINKED ISSUE #241: LSPSaga is incompatible with latest nightly due to handler change
We merged https://github.com/neovim/neovim/pull/15504 which changes the signature of the built-in handlers.

lspsaga has not been updated, and is no longer compatible with the latest nightly. If users' are interested in the functionality of lspsaga, I would a community members forks and updates the handler until development is resumed.

### PR DESCRIPTION
**Pull request by al3xfischer**
I created a PR to fix the incompatibility with nvim +nvim0.5.1.  Fixes #241.  All credits to @GustavoKatel and @tami5.  I just cherry-picked their changes.

### CODE REVIEW

**Comment by vinicius507** [comment]
This PR fixes Code Actions, but it seems like the `hover_doc` feature is still not working.

**Comment by GustavoKatel** [comment]
@vinicius507 looks like @tami5 fixed in this PR https://github.com/tami5/lspsaga.nvim/pull/10

**Comment by vinicius507** [comment]
> @vinicius507 looks like @tami5 fixed in this PR https://github.com/tami5/lspsaga.nvim/pull/10

Great, thanks!

**Comment by BitInByte** [comment]
Any date on releasing this fix?

**Comment by glepnir** [comment]
@al3xfischer  please update pr.

**Pull request closed without merging**
