### PR TITLE
Fix truncation of paths for finder provider

### PR DESCRIPTION
**Pull request by weilbith**
Fixes: #24

See the commit message for the details.

### CODE REVIEW

**Comment by weilbith** [comment]
Btw: @glepnir do you use Windows?

**Comment by glepnir** [comment]
I don't use windows.

**Comment by weilbith** [comment]
> I don't use windows. 

Ah okay. Was just a wild guess why you might not observed this issue yourself. Because of the backslashes in Windows paths. :shrug:

Thanks for accepting the PR. :hugging:

**Comment by glepnir** [comment]
There has a problem that if filepath does not match root_dir or home dir it will got nil so i add a patch for this

**Comment by weilbith** [comment]
Yes makes sense to add this case. :+1:

**Pull request merged**
