### PR TITLE
fix(symbolwinbar): Extra space on non-icon buffer

### PR DESCRIPTION
**Pull request by nullchilly**
Also, the current winbar behavior is not very good
If `vim.wo.winbar = nil` then it will not remove the extra one line. However `vim.wo.winbar = ""` does... Upstream bug?

https://user-images.githubusercontent.com/56817415/177960834-8f1efa04-cb42-4dc7-b179-5fff209687ec.mp4

in_custom manage to overcome this because I pattern matching every buffer

https://user-images.githubusercontent.com/56817415/177961447-5c8a2106-57df-4712-b3b6-4facdac0c218.mp4

### CODE REVIEW

**Comment by glepnir** [comment]
`:h winbar` you can't set it to nil. default is empty

**Comment by glepnir** [comment]
hmm works fine with me ?

image

**Comment by nullchilly** [comment]
@glepnir https://github.com/neovim/neovim/issues/18660 upstream issue

**Comment by glepnir** [comment]
I think it should be work like statusline/tabline.

**Comment by nullchilly** [comment]
Sure, I think it's a preference

Either way, I provided a way to disable it if they want in this pull request. Please review

**Comment by nullchilly** [comment]
Thanks @glepnir

I saw you joined the neovim core, wish you luck for the foreseeable :)

Taking a break from the internet for a while, thanks for merging these silly pull requests!

**Comment by glepnir** [comment]
oh I had joined for a while . now i public my organizations team information. so you saw it :)

 There are some code not very readable in example . I had edit it . a reusable table should not be defined inside a function. Memory allocation is unscientific

**Comment by glepnir** [comment]
@nullchilly  hi did you found symbol winbar very slow in lua file today?

**Comment by nullchilly** [comment]
@glepnir It's faster actually lol

**Pull request merged**
