### PR TITLE
feat: add option to configure width and border style

### PR DESCRIPTION
**Pull request by elianiva**
This PR adds 2 new options to set the max width of hover window and its border style.

### CODE REVIEW

**Comment by glepnir** [comment]
LGTM:) Thanks.

**Comment by glepnir** [comment]
Bug with max_hover_widht it will hung neovim.

**Comment by elianiva** [comment]
Ah, my bad. I didn't test if it has `0` value.

**Comment by elianiva** [comment]
Ok I have a fix for that, turns out it `_make_floating_popup_size` is using `max_width` that we provided. The solution is just renaming `max_width` in `handler.lua` to `max_hover_width`. Do you want me to make a PR for this?

**Pull request merged**
