### PR TITLE
Use highlight groups to adjust color appearance

### PR DESCRIPTION
**Pull request by weilbith**
Second attempt after #42 
@glepnir please give it another try on this branch. As I said should the reset color logic just work fine. :shrug:

### CODE REVIEW

**Comment by glepnir** [comment]
Okay test now. Thanks for  PR sorry for revert:)

**Comment by glepnir** [comment]
Aha I know what happen. If remove these code that will be not work

```lua
  api.nvim_command('hi! CursorLine  guibg='..self.cursor_line_bg)
  if self.cursor_line_fg == '' then
    api.nvim_command('hi! CursorLine  guifg=NONE')
  end
```

**Comment by glepnir** [comment]
Thnaks for PR. merged now.

**Comment by weilbith** [comment]
Haha, alright. Thanks for your time!

**Comment by glepnir** [comment]
It's okay

**Pull request merged**
