### PR TITLE
fix:fix diagnostic border highlight group

### PR DESCRIPTION
**Pull request by zhaogangang**

### CODE REVIEW

**Comment by glepnir** [comment]
it's design follow the diagnostic type.

**Comment by zhaogangang** [comment]
DiagnoticErrBorder in highlight.lua, so i think border's hl group shoud be DiagnoticErrBorder

**Comment by glepnir** [comment]
nope. highlight should remove.

**Comment by zhaogangang** [comment]
alright

**Comment by glepnir** [comment]
does this feature not works well or what do you want ? you changed it to `diagnosticErrborder` it also linked to diagnosticerror

**Comment by zhaogangang** [comment]
i just want to change diagnotic border hl, right now, changed DiagnoticError may be work well for me

**Comment by glepnir** [comment]
can add option for this. follow = true. will add in #810 next version.

**Comment by glepnir** [comment]
if add this option it will be `diagnosticborder` . every diagnostic type window border will both use this highlight .

**Comment by zhaogangang** [comment]
i got it, thank you anwser

**Pull request closed without merging**
