### PR TITLE
Fix hover_doc

### PR DESCRIPTION
**Pull request by yuki-yano**
Related: #674 #688

Fixed an error in tsserver due to incorrectly positioned code for converting contents.

### CODE REVIEW

**Comment by glepnir** [comment]
just wonder why it behind the parser content.  when request done . we should check result first.   then check result.content after parse. so it should .

```lua
if not result or not result.content then
return
end

parse result.content
....

**Comment by yuki-yano** [comment]
Sorry, I fixed it to work, but I think the code was wrong and I will check it.
However, the current code sometimes has a string in `result.contents`, so I get an error at `next(result.contents)`.

**Comment by glepnir** [comment]
yes . res.content not always table so remove this check `next(result.content) == nil`

**Comment by yuki-yano** [comment]
Thank you. Should I delete this PR?

**Comment by glepnir** [comment]
you can just remove this `or next(result.contents) == nil `

**Comment by yuki-yano** [comment]
Modified PR to remove only the part that uses next.

**Comment by glepnir** [comment]
Thanks

**Pull request merged**
