### PR TITLE
refactor peek_definition more  easy to use and more useful

### PR DESCRIPTION
**Pull request by glepnir**
remove `close back next` keymaps in peek_definition.  if you want go back prev definition just `<C-o>` .

### CODE REVIEW

**Comment by glepnir** [comment]
@scottming can you test this version `peek_definition` ?

**Comment by scottming** [comment]
I didn't find any major bugs for now. I like it.

And this area is no need. 

image

**Comment by scottming** [comment]
Got it, Leaving the line number doesn't affect me too much. Just leave it. Reliability is always the most important thing.

Thanks for your work.

**Comment by scottming** [comment]
I found another bug, these update will break the normal `ctrl-o`

before peek: goto definition -> ctrl-o can back
after `peek_definition` and `q`: goto definition -> ctrl-o do nothing.

https://user-images.githubusercontent.com/12830256/220334237-c9ed4f5f-3f93-4242-8aa2-65a15d981dc5.mp4

**Comment by glepnir** [comment]
you opened new window the pos is changed.

**Comment by glepnir** [comment]
and in my test it works  fine ?
lsp

**Pull request merged**
