### PR TITLE
Fix finder preview window size issues

### LINKED ISSUE #204: Finder preview window not showing up properly
### Description
When I use `:Lspsaga finder` and I go through the results, the preview window usually doesn't appear, when it does, it uses scarcely little space, so little it is barely useful.

**Expected Behavior**
Expecting a file preview popup window to show when enough space provided.

**Actual Behavior**
When in fullscreen (1920x1080) with no splits, no preview is showing next to the finder window:
Horizontal orientation
Same goes for vertical orientation (1080x1920).

But if I rotate the screen from horizontal to vertical, with the finder window already opened, it finally pops up at least next to the finder, where it has less space than under the finder:
Vertical with finder already present
Same goes for opening the finder in vertical orientation and then switching to horizontal orientaiton.

### Details

Try `:Lspsaga finder`, nothing else I am aware of - I use the default settings.

- nvim --version output:
```
NVIM v0.5.0-dev+1345-g6dd04ed5f
Build type: RelWithDebInfo

LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS     -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/kepis/.cache/paru/clone/neovim-nightly-git/src/build/config -I/home/kepis/.cache/paru/clone/neovim-nightly-git/src/neovim-nightly-git/src -I/usr/include -I/home/kepis/.cache/paru/clone/neovim-nightly-git/src/build/src/nvim/auto -I/home/kepis/.cache/paru/clone/neovim-nightly-git/src/build/include
```
- Operating system: ArchLinux
- lspsaga commit: #181

### PR DESCRIPTION
**Pull request by jasonrhansen**
Fixes #204 and #190

### CODE REVIEW

**Comment by sieuwerts** [comment]
What's the status on this PR?

**Comment by glepnir** [comment]
hmm I will check in next weekend because I am in hospital

--------------原始邮件--------------
发件人："sieuwerts ***@***.***&gt;;
发送时间：2021年6月17日(星期四) 晚上7:08
收件人："glepnir/lspsaga.nvim" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [glepnir/lspsaga.nvim] Fix finder preview window size issues (#207)
-----------------------------------

 

 
What's the status on this PR?

**Comment by sieuwerts** [comment]
> hmm I will check in next weekend because I am in hospital
Don't stress it, feel better first. 👍

**Comment by jasonrhansen** [comment]
@glepnir Oh no, I hope you're doing ok. Get well soon!

**Comment by tami5** [comment]
> hmm I will check in next weekend because I am in hospital

😢 hope you are okay.

**Comment by rsheasby** [comment]
For anyone else that stumbles upon this issue and wants a temporary solution while waiting for @glepnir to get a chance to review (hopefully you're doing well), you can temporarily replace your plugin line with this:

`Plug 'jasonrhansen/lspsaga.nvim', {'branch': 'finder-preview-fixes'}`

Then remember to `PlugClean` and `PlugInstall`.

 I've confirmed that @jasonrhansen 's fix does work correctly, and it's currently not behind master at all. Once @glepnir finds the time to review, obviously replace it back with the regular path.

**Comment by ionnux** [comment]
Thanks

**Comment by jamesob** [comment]
This patch works well for me; prior to using this branch, the preview window was very small and almost unusable. This seems to fix things and the code looks good.

**Comment by chroth7** [comment]
can confirm too, works as expected now

if anybody is using Packer: 
```
  -- use 'glepnir/lspsaga.nvim'
  use {'jasonrhansen/lspsaga.nvim', branch = 'finder-preview-fixes'}
```
as temp fix 

Get well soon @glepnir all the best

**Comment by tami5** [comment]
Till @glepnir  go back, there's a temporary repo for hotfixes https://github.com/tami5/lspsaga.nvim.

**Pull request merged**
