### PR TITLE
Add method for diagnostics under the cursor

### PR DESCRIPTION
**Pull request by tapayne88**
First off, love the plugin!

I wanted something similar to my CoC setup which shows all LSP diagnostics under the cursor position. I don't _think_ there is a way to do that with the existing API so I've added a new function to expose it.

```lua
require("lspsaga.diagnostic").show_cursor_diagnostics()
```

What do you think?

### CODE REVIEW

**Comment by glepnir** [comment]
This mean show diagnostic msg for cursor word  right?

**Comment by tapayne88** [comment]
Thanks for merging! Yeah, this should filter down all LSP errors for the current buffer to show just the errors for the current cursor position (likely the cursor word).

**Comment by glepnir** [comment]
@tapayne88  Hmm I must say sorry to you. I had rewrite diagnostic with neovim upstream .so you need reimplement it in current diagnostic of lspsaga.

**Comment by tapayne88** [comment]
Ah, no worries! I'll take a look 👍

**Pull request merged**
