### PR TITLE
enhance window behavior

### LINKED ISSUE #50: feat: enhance hover doc format
Hi there! Is it possible to make the first row on the hover doc to be multiple lines? eg.

image

I expect the first separator line to get placed at the line where that is marked with a red line. This is causing some issue when it doesn't have enough space until the `{` symbol so the highlight got messed up. Here's an example

image

Thanks in advance!

### PR DESCRIPTION
**Pull request by glepnir**
Enhance the hover doc window behavior. try close #50  #48

@elianiva  @akinsho Hi can you test this patch

### CODE REVIEW

**Comment by akinsho** [comment]
Will try in a few hours not by my computer at the moment

**Comment by glepnir** [comment]
Okay,not a complete patch. need support scroll in doc buffer.

**Comment by glepnir** [comment]
use `lua require('lspsaga.hover').scroll_in_hover()` to scroll hover doc

**Comment by elianiva** [comment]
I believe this is still a WIP because the window stays there when I move my cursor :laughing:

image

Here's the error message.

```
Error executing vim.schedule lua callback: ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/window.lua:321: Cannot convert given lua table
```

**Comment by glepnir** [comment]
@elianiva  can you test now?

**Comment by elianiva** [comment]
Great! It works now.

**Comment by akinsho** [comment]
@glepnir I still haven't tried it yet and it doesn't have to be part of this change but it looks like the scrolling only goes in one direction, why not take an argument like -1 or 1 so you can map to different keys and go up and down

**Comment by glepnir** [comment]
I forget scroll up support it later

**Comment by akinsho** [comment]
Awesome just tried this out @glepnir and it works nicely 🚀 great work.

When you get to doing scrolling (no rush) just a small recommendation would be to do it similarly to how `coc` handles the mapping e.g.
```lua
  map("n", "<C-f>", [[coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"]], nowait)
```
basically it provides a utility function to see if the floating window for the plugin is open then allows you to map it in a way that you can use normal scroll commands but if the hover window is open then it will scroll that instead

**Comment by akinsho** [comment]
Sorry one last point, also just realised that this doesn't apply to the finder window
image

**Comment by elianiva** [comment]
Probably not related but is there any way to attach an autocmd to lsp_finder? I want to attach an autocmd that hides my cursor but the filetype is `plaintext` and the buftype is `nofile` which isn't specific to lsp finder.

**Comment by glepnir** [comment]
@akinsho  @elianiva  new change

1. custom finder action keymap 
```
finder_action_keys = {
   open = 'o', vsplit = 's',split = 'i',quit = 'q'
},
```
2. smart height width of finder and hover doc so I think can remove `max_hover_doc_width`
3. support scoll hover doc not jump into it
```lua
lua require('lspsaga.hover').has_saga_hover() --true mean has hover doc --false not
lua require('lspsaga.hover').scroll_in_hover(1 or -1)  -- 1 mean scroll down -1 mean scroll up
```

**Comment by glepnir** [comment]
when test ok I will merge.

**Comment by akinsho** [comment]
🤔 just tested it out and the finder window is still really long not sure if I'm missing something

**Comment by glepnir** [comment]
now should be  works.

**Comment by akinsho** [comment]
Awesome that works now 👍🏿

**Comment by glepnir** [comment]
@akinsho  If no other problems I will merge this pr.

**Comment by akinsho** [comment]
Sounds good to me, this resolves my height issues 💯

**Comment by elianiva** [comment]
ditto, everything works well.

**Comment by akinsho** [comment]
For the future @glepnir I just noticed the signature window behaves the old way, maybe that could needs updating as well
image

**Comment by glepnir** [comment]
support it tomorrow

**Comment by glepnir** [comment]
@akinsho  done.

**Comment by glepnir** [comment]
smart scroll hover doc, if window has hover doc it will scroll hover , if not it will do <C-f>
```lua
-- scroll down hover doc
nnoremap <silent> <C-f> <cmd>lua require('lspsaga.hover').smart_scroll_hover(1)<CR>
-- scroll up hover doc
nnoremap <silent> <C-b> <cmd>lua require('lspsaga.hover').smart_scroll_hover(-1)<CR>
```

**Comment by akinsho** [comment]
Just tested this out @glepnir I still see

image

It looks like it's moved but the width is still really small. You can reproduce by typing `print(<cursor>`.

**Comment by glepnir** [comment]
`echo winwidth(0)` output

**Comment by glepnir** [comment]
should be works now.

**Comment by akinsho** [comment]
@glepnir yep that's fixed it thanks 👍🏿

**Pull request merged**
