### PR TITLE
Add a ui.kind change example to the README.md

### PR DESCRIPTION
**Pull request by scottming**

### CODE REVIEW

**Comment by glepnir** [comment]
it support value is string or type 
```lua
['Folder'] = 'highlight group name' or  { icon, 'highlight group name'} 
```

**Comment by scottming** [comment]
if just use string, the change won't work

for example:

```
	ui = { kind = { ["Folder"] = "@comment"  }, },
```

the UI changed to:

image

**Comment by glepnir** [comment]
fixed.

**Comment by scottming** [comment]
> fixed.

updated.

**Comment by glepnir** [comment]
commit message a little dirty . can you squash ?

**Comment by scottming** [comment]
Sorry, I'm not skilled in squash; I noticed you merged before I squashed.

There is some typo in that sentence; can you change it yourself?

```
The key in `ui.kind` is the kind name, and the value can either be a string or a table. If a string is passed, it is setting the `icon`. If table is passed, it will be passed as `{ icon, highlight group }`. For example, to change the folder's icon color, you could do this: `ui = { kind = { ["Folder"] = { " ", "@comment" }, }, },` or `ui = { kind = { ["Folder"] = "@comment" }, },`.
```

**Pull request merged**
