### PR TITLE
version 0.2.9

### LINKED ISSUE #930: feature request: diagnostic jump show more informations
Can lspsaga diagnostic_jump_next/prev shows all message in `title` ? I know `Lspsaga show_line_diagnostics` can show all message.

if worth to do, may provide an option to enable would be better I think, e.g. `lspsaga.diagnostic.show_more_information`, defaults to `false`

---

`vim.diagnostic.goto_next`

image

`lspsaga diagnostic_jump_next`

image

### LINKED ISSUE #940: [Finder Ui] better window behavior
I have a small screen, and when using `Lspsaga lsp_finder`, the _preview_ section is really small (see screenshot).

Would it be possible to add a feature to move the preview window under the list of files? Or/and maybe edit the list of files so that they get truncated or something...

image

### LINKED ISSUE #941: finder 窗口宽度不够时显示错误
### Describe the bug

窗口宽度不够时显示错误

### Steps to reproduce

image

红线代表窗口宽度

### Expected behavior

image

加长宽度后显示正常

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

db6cdf51bf5ae45e4aa65760e597cf0d587c66ee

### Terminal name/version

neovide/ 0.10.0

### LINKED ISSUE #943: Set preview width for `outline`
**Is your feature request related to a problem? Please describe.**
When using `:Lspsaga outline`, if the indentation is more than a few tabs, the preview is not wide enough to provide enough context. In the screenshot below, the preview window does not help me in any way.

image

**Describe the solution you'd like**
A paramater to configure the preview width through the `outline` config. 
#556 mentioned this, but I could not find the solution implemented for this issue.

**Describe alternatives you've considered**
I did not find a way to set the preview width.

### LINKED ISSUE #950: Omnisharp Definition Issues
### Describe the bug

Trying to access definitions for any Omnisharp System types fails. I get Cursor position outside buffer stack traceback, as well as E79: Cannot expand wildcards.

I have Omnisharp installed globally, on my computer. I know the metadata should be available. 

No problem accessing definitions in other IDE's. 

### Steps to reproduce

Lsp go_to_definition on any system types like int System.Console, Dictionary, etc, in .NET 6/7 using C#. 

### Expected behavior

Show metadata information about that type. 

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3

### lspsaga commit

commit db6cdf5

### Terminal name/version

iTerm2 Build 3.4.16

### LINKED ISSUE #953: peek_definition jump list problem
### Describe the bug

When I use peek_definition and press `q` to close floating window then `<C-o>` and `<C-i>` (jump list navigation)  stops to work. I know documentation says I can press <C-t> but why <C-o> & <C-i> are being broken?
Is this bug or a feature?

### Steps to reproduce

1. With rust lsp attached use `Lspsaga peek_definition` command to peek function definition
2. Press `q` to close popup
3. Use `Lspsaga goto_definition` or default lsp goto_definition command on that function
4. Try press <C-o> - it doesn't move cursor back to position from step 3

### Expected behavior

<C-o> and <C-i> should work 

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

peek_definition

### Terminal name/version

kitty 0.27.1

### LINKED ISSUE #955: Navigate links inside `hover_doc`
Make it possible to navigate links inside `hover_doc`, like in image:

### LINKED ISSUE #958: Without nvim-web-devicons installed, this plugin constantly blocks the UI with warnings
### Describe the bug

Hey, thanks for the amazing OSS effort!

It seems that with a recent release of this plugin, the web dev icons are now a mandatory requirement?

I don't like viewing the icons, and previous releases I was able to disable them, but it seems that in the current release, not only can I not seem to remove them from the UI (there seems to be no way of removing `kind` icons from the symbol winbar), but more importantly the constant warnings from [this function](https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/libs.lua#L25) block my workflow consecutively.

Would you accept a PR for a `ui.icons = false` config option to bail out of that devicons method early? If so I can submit one.

### Steps to reproduce

Run this plugin without the nvim-web-devicons plugin installed.

### Expected behavior

Icons should not be displayed, and the plugin should continue silently.

### Neovim version (nvim -v)

NVIM v0.8.3

### lspsaga commit

44ae62d

### Terminal name/version

iTerm2, Build 3.4.19

### LINKED ISSUE #962: Opening the finder causes syntax highlighting to change?
### Describe the bug

Opening the finder causes syntax highlighting to change. Very strange behaviour, visible here:

https://user-images.githubusercontent.com/6242344/227183058-7f7c9fc7-d3d6-4917-9d37-809041d08394.mov

`syntax`, `colorscheme` and `filetype` are all correct before and after the change. Are you aware of anything that might cause this? It wasn't happening before I updated to the latest version of this plugin.

### Steps to reproduce

Install the plugin and tokyonight, this is run on a Typescript file. Can provide minimal recreation or further details if needed

### Expected behavior

The highlighting does not change.

### Neovim version (nvim -v)

NVIM v0.8.3

### lspsaga commit

44ae62d

### Terminal name/version

iTerm2, Build 3.4.19

### LINKED ISSUE #964: Triggers code_action even if diagnostics popup already closed
### Describe the bug

Hello, I would like to thank you for this amazing plugin, it makes my work more efficient but I found some strange behavior. 

When jump between diagnostics (`diagnostics_jump_next / diagnostics_jump_prev`) and select one of provided code_action by index (for example 1 index) popup window is closing and lspsaga executing selected code_action, this works great but when later after executing `code_action` I click some number, for example 12-j for jumping 12 lines down lspsaga executing one of `code_action`, because of number 1. 

### Steps to reproduce

`diagnostics_jump_next()`
select one of `code_action`, for example first one by clicking 1
after diagnostics popup closed type 1 again

### Expected behavior

when diagnostics popup closed it should not trigger `code_action` any more

### Neovim version (nvim -v)

0.8

### lspsaga commit

??

### Terminal name/version

iterm2

### LINKED ISSUE #965: [Feature Request] Allow to use the same key for expand_collapse + open in outline
In the outline  want to use `<CR>` for both:
 * Expand/collapse when on a headline
 * Open when on a method, prop, etc.

Right now that's not possible. 

But both situations can never interfere so I think it makes sense to use the same key.

If you used `<CR>` you'd get the same behavior as with e.g. nvim-tree: expand/collapse when on a directory and open when on a file.

### PR DESCRIPTION
**Pull request by glepnir**
## Finder

The finder ui and performance were refactored. To make it more useful and responsive on large projects. the old `finder.keys.edit` has been removed. instead of is `finder.keys.expand_or_jump`. then you can use this key to expand or collapse on file name line jump in code preview line. see video in next comment.

## Hover

Add a status checker. To avoid frequent hover requests when the server is still initializing.
support open link in hover by `hover.open_link` default is `gx` and `hover.open_browser` default is `chrome`.  also support open a file link in neovim. see next comment video.

## Diagnostic Jump

new option `extend_relatedInformation`. default is false when is true it will extend the `relatedInformation` message into the diagnostic message works like `vscode`.

image

remove `Lspsaga show_cursor_diagnsotic` . now the diagnostic jump next or prev will show the diagnostic in cursor first if cursor have diagnositc.

code action preview in diagnostic in jump support scroll to preview action in your current buffer by `scroll_preview.scroll_down` and `scroll_preview.scoll_up` default is `<C-f>` and `<C-b>`.  new icon is `ui.actionfix` option.

diagnsotic_jump

## Diagnostic show

now the show diagnostic is refactored. `show_cursor_diagnostic` is removed .  add the `show_workspace_diagnsotic`.
related option `diagnsotic.max_show_width` `diagnsotic.max_show_height` to config the show window width and height.
`diagnositc.keys.expand_or_jump` `diagnsotic.quit_in_show` keymap use in show window. you can expand or collapse on file name line  and jump to location on message line. 

Tip: if you don't like the diagnostic message text highlight follow the diagnostic type in jump window or show window you can use `diagnostic.text_hl_follow` to false to disable then the highlight `DiagnosticText` is used.

`show_buf_diagnsotic`  `show_line_diagnsotic` `show_workspace_diagnostic` ui is same. eg:

image

## Outline
remove `outline.jump` `outline.expand_or_collapse` . new option is `outline.expand_or_jump` default is `o`. 
add `outline.preview_width` default is `0.4`

### Misc
code optimize. some bug fix. relate issue

Fix #930  Fix #940 Fix #941 Fix #943 Fix #950 Fix #953 Fix #955 Fix #958 Fix #962 Fix #964 Fix #965

### CODE REVIEW

**Comment by glepnir** [comment]
image

**Comment by glepnir** [comment]
image

**Comment by glepnir** [comment]
https://user-images.githubusercontent.com/41671631/227209443-7c719122-e389-4e0e-aecf-8ac0f7f3f61f.mov

**Comment by glepnir** [comment]
https://user-images.githubusercontent.com/41671631/227512110-d115ae72-2194-40b8-9f6d-c92bc319499c.mov

**Comment by glepnir** [comment]
image

**Comment by mikehaertl** [comment]
@glepnir Nice work. Could you also update the README and the docs?

**Comment by glepnir** [comment]
in mind. later.

**Comment by glepnir** [comment]
image

**Comment by AndreM222** [comment]
does it require netrwPlugin?

**Pull request merged**
