### PR TITLE
fix(lightbulb): use passed in bufnr

### PR DESCRIPTION
**Pull request by Littledarren**
the current buffer may have been changed during coroutine running and that causes an error.

### CODE REVIEW

**Comment by glepnir** [comment]
LGTM

**Comment by XXiaoA** [comment]
> the current buffer may have been changed during coroutine running and that causes an error.

Hi, after merging your PR, nvim threw the error everytime when I'm in `i` mode and move the cursor
img

**Comment by glepnir** [comment]
`sign_unplace` can't use  0, `0` it's a highly function in neovim api-fast.

**Comment by Littledarren** [comment]
Sorry for the error. I passed bufnr= 0 and want it to be the default current buffer num which fails. Need I give a quick patch or pr?

**Comment by Littledarren** [comment]
I've seen the fix, sorry for the bug...抱歉hh

**Pull request merged**
