### PR TITLE
use codeaction quit key on rename

### PR DESCRIPTION
**Pull request by windwp**
I want to use <esc> for close rename . 
i add this mapping to reuse code action quit key

### CODE REVIEW

**Comment by glepnir** [comment]
There has a problem if the new name of func has a word `q` .the default quit key will be trigger. then quit the rename window.

**Comment by windwp** [comment]
Now I only add esc to quit on  insert mode.If  i use a default action rename  on lsp i can esc to quit.

**Comment by glepnir** [comment]
I think we can make it optional ? like` rename_keys = { quit = 'q',exec='<CR>'}`

**Comment by windwp** [comment]
but you can't map q in insert mode. the only key can do that in insert mode is <esc>.

**Comment by glepnir** [comment]
just example I mean config like code_action keys. that user can custom it.

**Comment by windwp** [comment]
in insert or normal mode?

**Comment by glepnir** [comment]
```lua
rename_keys = { quit = 'q' or table type {'q','<Esc>','<C-c>'}   ,exec = '<CR>'}  
```
quit is keys in insertmode . normal mode we can hardcored q  and esc ?

**Comment by glepnir** [comment]
close by ad0ce56

**Pull request closed without merging**
