### PR TITLE
Use highlight groups to adjust color appearance

### LINKED ISSUE #41: Use custom highlight group for selection in finder
You recently added the ability to change colors to highlight the current active entry in the finder. This is configured by two color values. I think it would be cool if you would add a new custom highlight group and then link the cursor line to this group. This still allows the user to easily change the highlight. But instead of defining raw color values you could also create a highlight link. So for example would I link it to the `Search` highlight group of my theme. But now I need to copy paste the colors. And I can't even apply "effects" like bold text. And now if I change my theme, I must also change the colors here again...
Would be a cool addition.

---

Btw: your recent improvements on the finder window are great! :muscle:

### PR DESCRIPTION
**Pull request by weilbith**
Fixes #41

### CODE REVIEW

**Comment by glepnir** [comment]
Then I think we do not need these code right?
https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/provider.lua#L360-L365

**Comment by weilbith** [comment]
> Then I think we do not need these code right?
> https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/provider.lua#L360-L365

Oh, I haven't seen this. What's its exact purpose? I don't understand it completely...

**Comment by glepnir** [comment]
I got a problem that if we quit the `lsp finder` window. the highlight of `CursorLine` need reset .

**Comment by weilbith** [comment]
Ah yeah. This should be still an issue, as we use a regular group. If we would do the highlighting ourselves this would be fine. But for changing the cursorline we still need this reset logic.
So for the moment it still works as I see it. We could think about alternating the solution to get rid of the "get back to old highlight" logic.

**Comment by weilbith** [comment]
Why did you reverted it? It should just work. Or what is the issue?

**Comment by glepnir** [comment]
when i quit the `finder` window ..the `CursorLine` use `LspSagaSelction` bg color ..so I revert it. didi you test it in your local ?

**Comment by weilbith** [comment]
Really? For me it does not. I mean in fact it is the same as before. Your reset logic should be still there. I basically just changed the definition part...

**Comment by weilbith** [comment]
I tried it again. And it works. So do you have an explanation why your former reset logic does not work anymore?

**Comment by glepnir** [comment]
hmm why does not work for me . I run `git pull` then does not work..so revert it sorry. can you create a pr again I will check what happen . current I am fix the issue of diagnostic.

**Comment by weilbith** [comment]
> hmm why does not work for me . I run git pull then does not work..so revert it sorry. 

No problem. Correct reaction.

> can you create a pr again I will check what happen .

Sure. :100: 

> current I am fix the issue of diagnostic.

What is it about? I don't see an open issue regarding this.

**Comment by glepnir** [comment]
check here #30

**Pull request merged**
