### PR TITLE
Move to new _trim since _trim_and_pad no longer exists

### LINKED ISSUE #164: Attempt to call field '_trim_and_pad' (a nil value)
### Description

Issuing the commands `:Lspsaga hover_doc` or `:Lspsaga show_line_diagnostics` give me an error where `_trim_and_pad` function does not exist.

This is probably (not sure exactly) due to [this PR](https://github.com/neovim/neovim/pull/14207) in neovim where the `trim_and_pad` function was removed from their utility file.

**Expected Behavior**

Should show popup menu with the definition preview or diagnostic info.

**Actual Behavior**

image

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. Have nvim-lspconfig and lspsaga installed
2. Register the lsp via `require 'lspconfig'.tsserver.setup { on_attach = function(client) print('Attached to '.. client.name) end }`
3. Open a file supported by nvim-lsp (eg javascript/typescript file with typescript-language-server installed)
4. Run the command `:Lspsaga hover_doc`
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1225-gbbdd00203
- Operating system: Windows 10 using WSL2 (Ubuntu 20.04)
- lspsaga commit: 27c7a47

</details>

### PR DESCRIPTION
**Pull request by ckipp01**
https://github.com/neovim/neovim/pull/14207
Fixes #164

### CODE REVIEW

**Comment by lynndylanhurley** [comment]
This solves the problem for me 👍

**Comment by mjlbach** [comment]
I would not recommend using functions in core prefixed with _ as we consider those internal use only.

**Comment by glepnir** [comment]
> we may just remove _trim and use trim_empty_lines instead

yup.

**Comment by tami5** [comment]
I get errors after updating:

```
|| Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:290: attempt to call field '_trim' (a nil value)
```

**Comment by mjlbach** [comment]
You need to update your neovim nightly build

**Comment by tami5** [comment]
Thanks a lot @mjlbach. 

btw is there a way I can identify a pupbuffer. I'm working on markdown plugin and syntax and I'd like to enable conceal on a condition that matches lspsaga or lsp popup buffer

**Comment by jsatk** [comment]
```
$ brew update; and brew upgrade nvim
Already up-to-date.
Warning: nvim HEAD-9f5c822_2 already installed
```

I'm still getting this issue on the latest Neovim available in homebrew and the latest version of this plugin.

**Comment by jsatk** [comment]
Opened bug here: https://github.com/glepnir/lspsaga.nvim/issues/176

**Comment by mjlbach** [comment]
That commit is 21 days old, so I don't know what is going on with your homebrew setup.

**Pull request merged**
